default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: rails
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: resolution_management_development


test:
  <<: *default
  database: resolution_management_test
